### ISSUE TITLE
Bindists generate invalid code

### ISSUE THREAD

**Issue by hasufell** [redneb/ghc-alt-libc#13]
https://gitlab.haskell.org/ghc/ghc/-/issues/17508

I get the same with these bindists. integer-gmp must be used to fix this.

**Comment by redneb** [comment]
I do not have any such problem under gentoo/musl. Did you install the binaries using the `--disable-ld-override` flag for the `configure` script? I suspect this might be another manifestation of #6. This also seems to be Ben's suspicion in the GHC issue you linked.

**Comment by hasufell** [comment]
I've switched to manually build alpine bindists and lost track about how I fixed this, lol.
