### ISSUE TITLE
Additional information

### ISSUE THREAD

**Issue by noteed** [redneb/ghc-alt-libc#2]
I would like to know how these binaries were compiled. Did you use one of https://github.com/mitchty/alpine-linux-ghc-bootstrap or https://github.com/nilcons/ghc-musl ? How does your project relate to those ?

Thanks a lot

**Comment by redneb** [comment]
I think both project were inspired by or were even bootstrapped using my project. The second one explicitly mentions my reddit post in its readme file.

As for how these binaries were produced, I [explained it on reddit](https://www.reddit.com/r/haskell/comments/37m7q7/ghc_musl_easier_static_linking/crnytml):

> To produce these binaries, I followed the GHC [cross-compiling guide](https://ghc.haskell.org/trac/ghc/wiki/Building/CrossCompiling) all the way to stage 2. I did this in a glibc system. Then I took the resulting binaries and installed them in a musl based system and I recompiled GHC there (i.e. regular compilation, no cross-compiling) which went exceptionally smoothly. What I got from that step is what I posted here.

I guess it would be a good idea to include the above text to the notes here.

**Comment by noteed** [comment]
Thanks for the answer. I found reddit threads but somehow missed that one or didn't see it was you.
