### ISSUE TITLE
fails to compile libraries which use ffi?

### ISSUE THREAD

**Issue by 0x777** [redneb/ghc-alt-libc#3]
When I try to build `postgresql-libpq` or `entropy` package, the error message is as follows:
```bash
$ cabal new-build postgresql-libpq
Build profile: -w ghc-8.6.4 -O1
In order, the following will be built (use -v for more details):
 - postgresql-libpq-0.9.4.2 (lib:postgresql-libpq) (requires build)
Starting     postgresql-libpq-0.9.4.2 (all, legacy fallback)
cabal: Failed to build postgresql-libpq-0.9.4.2. The failure occurred during
the configure step. The build process segfaulted (i.e. SIGSEGV).
```

This is my build environment:
1. Built a docker image using the latest gentoo musl release from [here](stage3-amd64-musl-vanilla-20190304.tar.bz2).
2. Installed the musl variant of ghc 8.6.4 from this repo.
3. Downloaded musl variant of cabal from [here](https://www.haskell.org/cabal/download.html). 
4. Tried to build my project with cabal with `--keep-going`. The build fails on postgresql-libpq and entropy packages.

Did you ever encounter such errors? Both these packages seem to use ffi. 

P.S Thanks for the detailed docs on how to set the whole system up

**Comment by redneb** [comment]
I never had any issues with packages that use ffi. I just tried to install `entropy` and it worked:

    $ cabal v2-repl --build-depends=entropy
    Resolving dependencies...
    Build profile: -w ghc-8.6.4 -O1
    In order, the following will be built (use -v for more details):
     - entropy-0.4.1.4 (lib:entropy) (requires build)
     - fake-package-0 (lib) (first run)
    [1 of 1] Compiling Main             ( /tmp/cabal-repl.-9031/dist-newstyle/tmp/src-9031/entropy-0.4.1.4/dist/setup/setup.hs, /tmp/cabal-repl.-9031/dist-newstyle/tmp/src-9031/entropy-0.4.1.4/dist/setup/Main.o )
    Linking /tmp/cabal-repl.-9031/dist-newstyle/tmp/src-9031/entropy-0.4.1.4/dist/setup/setup ...
    Configuring entropy-0.4.1.4...
    Result of RDRAND Test: True
    Preprocessing library for entropy-0.4.1.4..
    Building library for entropy-0.4.1.4..
    [1 of 2] Compiling System.EntropyNix ( System/EntropyNix.hs, dist/build/System/EntropyNix.o )
    [2 of 2] Compiling System.Entropy   ( System/Entropy.hs, dist/build/System/Entropy.o )
    Installing library in /home/geo/.cabal/store/ghc-8.6.4/incoming/new-9031/home/geo/.cabal/store/ghc-8.6.4/entropy-0.4.1.4-2169c55942676b71b771b66a58826496ec9a91ac3130b60daaa84bd81c77d5ce/lib
    Configuring library for fake-package-0..
    Preprocessing library for fake-package-0..
    Warning: No exposed modules
    GHCi, version 8.6.4: http://www.haskell.org/ghc/  :? for help
    Prelude> System.Entropy.getEntropy 10
    ".q\155\&0QR\148\245\b\179"

Did you try to pass `-v -j1` to cabal when building?
