### ISSUE TITLE
Bindist doesn't install `haddock` binary

### ISSUE THREAD

**Issue by borsboom** [redneb/ghc-alt-libc#5]
The bindist in [ghc-8.6.5-x86_64-unknown-linux-musl.tar.xz](https://github.com/redneb/ghc-alt-libc/releases/tag/ghc-8.6.5-musl) doesn't appear to install `haddock` when installed using `./configure --prefix=… && make install` on Alpine Linux.

I haven't checked any other bindists, so not sure if this is specific to this bindist or applies to all of them.

(I'm investigating whether these bindists can be used to add first-class Alpine/musl support to Stack, and it's looking very promising aside from this.  See https://github.com/commercialhaskell/stack/issues/2387#issuecomment-500245212.)

**Comment by redneb** [comment]
I was under the impression that `haddock` is not built during the (default) `ghc` build process, it's just an independent package.

I did make the binaries with `HADDOCK_DOCS=NO`, but I don't think this has anything to do with building `haddock` itself; it simply controls whether the `*.haddock` files are generated.

Also, the linux binaries in the official ghc [download page](https://www.haskell.org/ghc/download_ghc_8_6_5.html#linux_x86_64) do not contain the `haddock` binary.

**Comment by borsboom** [comment]
[This GHC issue](https://gitlab.….org/ghc/ghc/issues/16407) implies that it's expected for official GHC bindists to include `haddock` (since it was a bug when it was missing from some Windows bindists).  I also verified with an official bindist:

```
# curl https://downloads.haskell.org/~ghc/8.6.5/ghc-8.6.5-x86_64-deb9-linux.tar.xz|tar xJf -
…
# cd ghc-8.6.5
# ./configure --prefix=/opt/ghc-8.6.5 && make install
…
# ls -l /opt/ghc-8.6.5/bin/haddock*
lrwxrwxrwx 1 root root  17 Jun 10 09:50 /opt/ghc-8.6.5/bin/haddock -> haddock-ghc-8.6.5
-rwxr-xr-x 1 root root 269 Jun 10 09:50 /opt/ghc-8.6.5/bin/haddock-ghc-8.6.5
```

Do you recall which BuildFlavour you're using to build these?  I think the official bindists use `perf`.

> I did make the binaries with `HADDOCK_DOCS=NO`

N.B.: Stack expects haddocks to be included with the bindist as well in order for `stack haddock` to work (since it doesn't rebuild packages that are included with GHC).

Of course you are welcome to package bindists however works for your use case, but it'd be beautiful if Stack could build on your excellent work putting together the bindists without extra duplication of effort.

**Comment by hasufell** [comment]
Are you sure you tested this without stack?

I tried 8.6.5 from this repository with ghcup and was able to install and use haddock just fine. You might be missing prerequisited like gmp-dev, libffi and ncurses-dev.

**Comment by redneb** [comment]
Well, it appears that `HADDOCK_DOCS=YES` causes `haddock` to be built and included in the binary-dist tarball. I will try to upload new binaries for 8.6.5 tomorrow.

**Comment by redneb** [comment]
I uploaded a new set of binaries for ghc 8.6.5 which include `haddock` and all the `*.haddock` files. Let me know if that works for you.

**Comment by borsboom** [comment]
That seems to work great!  It passes stack-2.1's more stringent sanity checks, and `stack haddock` works perfectly.  Thank you!
