### ISSUE TITLE
docker build fail with alpine images

### ISSUE THREAD

**Issue by leptonyu** [redneb/ghc-alt-libc#7]
I tried to build a docker image using ghc-8.8.1, but result in

```
Error relocating /opt/ghc/lib/ghc-8.8.1/bin/ghc-pkg: set_curterm: symbol not found
890make[1]: *** [ghc.mk:993: install_packages] Error 127
891make: *** [Makefile:51: install] Error 2
```

Detailed logs are showed in [build log](https://travis-ci.org/leptonyu/ghc-docker/builds/581540490).

What i miss?

**Comment by redneb** [comment]
Hi

Can you please provide more info? This project relies primarily on gentoo musl. I have tested my binaries under alpine in the past and they worked. Maybe your system is missing some of the dependencies? As mentioned in the [notes](https://github.com/redneb/ghc-alt-libc/blob/master/NOTES-musl.md), `libgmp.so.10` and `libncursesw.so.6` must be present in your system. Can you run something like:

    ls -lh {/usr,}/lib*/{libgmp,libncursesw}.so*

to check that they are indeed present in your system?

**Comment by leptonyu** [comment]
it shows 
```
bash-5.0# ls -l {/usr,}/lib*/{libgmp,libncursesw}.so*
ls: /lib*/libgmp.so*: No such file or directory
ls: /lib*/libncursesw.so*: No such file or directory
lrwxrwxrwx    1 root     root            16 Sep 13 04:21 /usr/lib/libgmp.so -> libgmp.so.10.3.2
lrwxrwxrwx    1 root     root            16 Sep 13 04:20 /usr/lib/libgmp.so.10 -> libgmp.so.10.3.2
-rwxr-xr-x    1 root     root        407264 May  3 10:29 /usr/lib/libgmp.so.10.3.2
lrwxrwxrwx    1 root     root            18 Sep 13 04:21 /usr/lib/libncursesw.so.6 -> libncursesw.so.6.1
-rwxr-xr-x    1 root     root        367560 May 28 10:53 /usr/lib/libncursesw.so.6.1
```

The build code is in [here](https://github.com/leptonyu/ghc-docker/tree/U881). I use travis to build the docker image.

**Comment by bjin** [comment]
I had the same issue, and adding the following line fixed it:
~~~dockerfile
RUN ln -sf /usr/lib/libncursesw.so.6 /usr/lib/libtinfow.so.6
~~~

**Comment by leptonyu** [comment]
@bjin It works, thank you.

**Comment by redneb** [comment]
Weird. I seem to recall that I had tried the same thing and it didn't work. Anyway, I am closing this since it worked for you.
